name: CI Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend-rails-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true
      working-directory: ./backend-rails-api
    - name: Run tests
      working-directory: ./backend-rails-api
      run: bundle exec rspec
